src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\SupplierRepository;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not an email address"
     * )
     */
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255)]
    private $company;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 5,
     *      minMessage = "Address too short"
     * )    
     */ 
    private $companyAddress;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Country(
     *      message = "this is not a valid country code"
     * )
     */ 
    private $country;

    #[ORM\Column(type: 'string', length: 8, nullable: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 5,
     *      max = 5,
     *      exactMessage = "Le Code Postal doit comporter 5 chiffres"
     * )
     */
    
    private $zipCode;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $region;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $RegistrationNumber;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $city;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $VATNumber;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Supplier $fkSupplier = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ApiToken::class, orphanRemoval: true,)]
    private Collection $apiTokens;

    public function __construct()
    {
        $this->apiTokens = new ArrayCollection();
    }

  

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getCompanyAddress(): ?string
    {
        return $this->companyAddress;
    }

    public function setCompanyAddress(?string $companyAddress): self
    {
        $this->companyAddress = $companyAddress;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(?string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(?string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getRegistrationNumber(): ?string
    {
        return $this->RegistrationNumber;
    }

    public function setRegistrationNumber(?string $RegistrationNumber): self
    {
        $this->RegistrationNumber = $RegistrationNumber;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getVATNumber(): ?string
    {
        return $this->VATNumber;
    }

    public function setVATNumber(?string $VATNumber): self
    {
        $this->VATNumber = $VATNumber;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFkSupplier(): ?Supplier
    {
        return $this->fkSupplier;
    }

    public function setFkSupplier(?Supplier $fkSupplier): self
    {
        $this->fkSupplier = $fkSupplier;

        return $this;
    }

    /**
     * @return Collection<int, ApiToken>
     */
    public function getApiTokens(): Collection
    {
        return $this->apiTokens;
    }

    public function addApiToken(ApiToken $apiToken): self
    {
        if (!$this->apiTokens->contains($apiToken)) {
            $this->apiTokens->add($apiToken);
            $apiToken->setUser($this);
        }

        return $this;
    }

    public function removeApiToken(ApiToken $apiToken): self
    {
        if ($this->apiTokens->removeElement($apiToken)) {
            // set the owning side to null (unless already changed)
            if ($apiToken->getUser() === $this) {
                $apiToken->setUser(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->email; 
      }


}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\EditProfileType;
use App\Form\RegistrationFormType;
use App\Repository\UserRepository;
use App\Security\LoginAuthenticator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface;

class ProfileController extends AbstractController
{
    #[Route('/profile', name: 'app_profile')]
    public function index(): Response
    {



        return $this->render('profile/index.html.twig', [
        ]);
    }

    #[Route('/profile/edit/{id}', name: 'app_profile_edit')]
    public function editProfile(
    Request $request, 
    UserPasswordHasherInterface $userPasswordHasher, 
    UserAuthenticatorInterface $userAuthenticator, 
    LoginAuthenticator $authenticator,
    EntityManagerInterface $entityManagerInterface,
    UserRepository $userRepository
    ): Response
    {

        $user = new User;
        /** @var \App\Entity\User $user */
        $user = $this->getUser();
        $id=$user->getId();
        $email=$user->getEmail();

        $form = $this->createForm(EditProfileType::class, $user);
        $form->handleRequest($request);

        //check submit  and valid from
            
        if($form->isSubmitted() && $form->isValid()){
            $newEmail=$user->getEmail();
        
            if ($this->isEmailExist($newEmail, $userRepository)===false || $newEmail == $email )  {
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                            $user,
                            $form->get('plainPassword')->getData()
                        )
                    );
            $this->updateUser($entityManagerInterface, $user);
            return $userAuthenticator->authenticateUser(
                $user,
                $authenticator,
                $request
            );
        }else{
            return $this->redirectToRoute('app_profile');
        }
    }

        return $this->render('profile/editProfile.html.twig', [
            'form' => $form->createView(),
            'id'=>$id
        ]);
    }  
    public function updateUser( EntityManagerInterface $entityManagerInterface,
        User $user,)
        {
            $entityManagerInterface->flush();
        }

    public function isEmailExist(string $emailUser,
    UserRepository $userRepository): bool
    {
        // search for an existing email in db
        $emailInDB= $userRepository->findOneBy(['email' => $emailUser]);

        if (!empty($emailInDB)) {
            return true;
        }
        return false;
    }
}

templates/profile/editProfile.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="container justify-content-center w-100 text-center">
    <div class="row justify-content-center">
     
<div class="col-12 col-lg-5">
    <h2 class="mt-5 text-white">Register</h2>
    {{ form_start(form) }}
        <label for="form_email" class="mt-2">Email</label>
        {{ form_row(form.email, {}) }}
        {{ form_row(form.plainPassword)}}
  
        
        <div class="row">
            <div class="col-6">
            <label for="form_firstName" class="mt-2">First name</label>
            {{ form_row(form.firstName, {}) }}
            </div>
            <div class="col-6">
            <label for="form_lasName" class="mt-2">Last name</label>
            {{ form_row(form.lastName, {}) }}
            </div>
        </div>
            <label for="form_company" class="mt-2">Company</label>
            {{ form_row(form.company, {}) }}

            <label for="form_companyAddress" class="mt-2">Company address</label>
            {{ form_row(form.companyAddress, {}) }}
            
        <div class="row">
            <div class="col-6">
            <label for="form_country" class="mt-2">Country</label>
            {{ form_row(form.country, {}) }}
            </div>
            <div class="col-6">
            <label for="form_region" class="mt-2">Region</label>
            {{ form_row(form.region, {}) }}
            </div>
         </div>
            
        <div class="row">
            <div class="col-6">
            <label for="form_zipCode" class="mt-2">Zip</label>
            {{ form_row(form.zipCode, {}) }}
            </div>
            <div class="col-6">
            <label for="form_city" class="mt-2">City</label>
            {{ form_row(form.city, {}) }}
            </div>
         </div>
            <label for="form_vatNumber" class="mt-2">V.A.T.</label>
            {{ form_row(form.vatNumber, {}) }}
            <label for="form_vatNumber" class="mt-2">Registration Number</label>
            {{ form_row(form.RegistrationNumber, {}) }}
            <div class="row justify-content-center">
                <button type="submit" class="btn btn-primary mt-3 w-50">Save edit</button>
            </div>
        {{ form_end(form) }}
        </div>
    </div>
 </div>
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}

<div class="container justify-content-center mt-5 w-100 text-center">
	<div class="row">
	<a class="btn btn-primary w-25" href="{{path('app_profile_edit' ,  { 'id': app.user.id})}}">Edit Profile</a>
	<table class="table mt-4">
			<thead>
				<tr>
					<th scope="col-6 col-lg-4"></th>
					<th scope="col-6 col-lg-4"></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">Email</th>
					<td>{{ app.user.email }}</td>
				</tr>
				<tr>
					<th scope="row">Firstname</th>
					<td>{{ app.user.firstname }}</td>
				</tr>
				<tr>
					<th scope="row">Lastname</th>
					<td>{{ app.user.lastname }}</td>
				</tr>
				<tr>
					<th scope="row">Company</th>
					<td>{{ app.user.company }}</td>
				</tr>
				<tr>
					<th scope="row">Country</th>
					<td>{{ app.user.country}}</td>
				</tr>
				<tr>
					<th scope="row">Zip Code</th>
					<td>{{ app.user.zipCode}}</td>
				</tr>
				<tr>
					<th scope="row">Region</th>
					<td></td>
				</tr>
				<tr>
					<th scope="row">City</th>
					<td>{{ app.user.city}}</td>
				</tr> 
				<tr>
					<th scope="row">Company Address</th>
					<td>{{ app.user.companyAddress}}</td>
				</tr> 
				<tr>
					<th scope="row">registration Number</th>
					<td>{{ app.user.registrationNumber}}</td>
				</tr> 
			</tbody>
		</table>
	</div>
</div>
{% endblock %}