src/Entity/Supplier.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\SupplierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SupplierRepository::class)]
#[ApiResource]
class Supplier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Reference;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $taxeRate;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $bankDetails;

    #[ORM\Column(type: 'string', length: 255)]
    private $companyName;

    #[ORM\OneToMany(mappedBy: 'supplier', targetEntity: Leads::class)]
    private Collection $fk_leadId;

    public function __construct()
    {
        $this->fk_leadId = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->Reference;
    }

    public function setReference(string $Reference): self
    {
        $this->Reference = $Reference;

        return $this;
    }

    public function getTaxeRate(): ?string
    {
        return $this->taxeRate;
    }

    public function setTaxeRate(?string $taxeRate): self
    {
        $this->taxeRate = $taxeRate;

        return $this;
    }

    public function getBankDetails(): ?string
    {
        return $this->bankDetails;
    }

    public function setBankDetails(?string $bankDetails): self
    {
        $this->bankDetails = $bankDetails;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->companyName;
    }

    public function setCompanyName(string $companyName): self
    {
        $this->companyName = $companyName;

        return $this;
    }

    /**
     * @return Collection<int, Leads>
     */
    public function getFkLeadId(): Collection
    {
        return $this->fk_leadId;
    }

    public function addFkLeadId(Leads $fkLeadId): self
    {
        if (!$this->fk_leadId->contains($fkLeadId)) {
            $this->fk_leadId->add($fkLeadId);
            $fkLeadId->setSupplier($this);
        }

        return $this;
    }

    public function removeFkLeadId(Leads $fkLeadId): self
    {
        if ($this->fk_leadId->removeElement($fkLeadId)) {
            // set the owning side to null (unless already changed)
            if ($fkLeadId->getSupplier() === $this) {
                $fkLeadId->setSupplier(null);
            }
        }

        return $this;
    }
    public function __toString(){    
        return $this->Reference;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\SupplierRepository;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not an email address"
     * )
     */
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255)]
    private $company;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 5,
     *      minMessage = "Address too short"
     * )    
     */ 
    private $companyAddress;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Country(
     *      message = "this is not a valid country code"
     * )
     */ 
    private $country;

    #[ORM\Column(type: 'string', length: 8, nullable: true)]
    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 5,
     *      max = 5,
     *      exactMessage = "Le Code Postal doit comporter 5 chiffres"
     * )
     */
    
    private $zipCode;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $region;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $RegistrationNumber;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $city;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $VATNumber;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Supplier $fkSupplier = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ApiToken::class, orphanRemoval: true,)]
    private Collection $apiTokens;

    public function __construct()
    {
        $this->apiTokens = new ArrayCollection();
    }

  

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getCompanyAddress(): ?string
    {
        return $this->companyAddress;
    }

    public function setCompanyAddress(?string $companyAddress): self
    {
        $this->companyAddress = $companyAddress;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(?string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(?string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getRegistrationNumber(): ?string
    {
        return $this->RegistrationNumber;
    }

    public function setRegistrationNumber(?string $RegistrationNumber): self
    {
        $this->RegistrationNumber = $RegistrationNumber;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getVATNumber(): ?string
    {
        return $this->VATNumber;
    }

    public function setVATNumber(?string $VATNumber): self
    {
        $this->VATNumber = $VATNumber;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFkSupplier(): ?Supplier
    {
        return $this->fkSupplier;
    }

    public function setFkSupplier(?Supplier $fkSupplier): self
    {
        $this->fkSupplier = $fkSupplier;

        return $this;
    }

    /**
     * @return Collection<int, ApiToken>
     */
    public function getApiTokens(): Collection
    {
        return $this->apiTokens;
    }

    public function addApiToken(ApiToken $apiToken): self
    {
        if (!$this->apiTokens->contains($apiToken)) {
            $this->apiTokens->add($apiToken);
            $apiToken->setUser($this);
        }

        return $this;
    }

    public function removeApiToken(ApiToken $apiToken): self
    {
        if ($this->apiTokens->removeElement($apiToken)) {
            // set the owning side to null (unless already changed)
            if ($apiToken->getUser() === $this) {
                $apiToken->setUser(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->email; 
      }


}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\LeadsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(AuthenticationUtils $authenticationUtils,
    ): Response
    {
  
        if($this->isGranted('ROLE_ADMIN')){
            return $this->redirectToRoute('admin');
        }    
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();
        return $this->render('home/index.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
            

        ]);
    }
    #[Route('/profile/result', name: 'app_profile_result')]
    public function resultSearch(AuthenticationUtils $authenticationUtils,
    LeadsRepository $leadsRepository,
    EntityManagerInterface $entityManagerInterface,
    ChartBuilderInterface $chartBuilder,
    ): Response
    {
        // Get current user
        $user = $this->getUser();
        $userId=$user->getId();
        $supplierId=$user->getFkSupplier()->getId();
       
       if (isset($_POST['search'])) {

            $startDate=$_POST['startDate'];
            $endDate=$_POST['endDate'];
            //id of the main campaign
            $campaignId= 1;
            $status='Accepted';
        $datesArr = getBetweenDatesAffiliates($startDate, $endDate);
        $dates =[];
        $leadPerday=[];
        
        foreach ($datesArr as $date) {
            $dates=$date."%";
            $leadPerdayArr=count($leadsRepository->selectLeadperday($dates, $campaignId, $supplierId, $status, $entityManagerInterface));
            $leadPerday[]=$leadPerdayArr;
        }
        $chart=chartSearchAffiliates($datesArr, $leadPerday, $chartBuilder);
       $resultsGlobal=$leadsRepository->selectLeadReportGlobal($startDate, $endDate, $campaignId, $supplierId, $status, $entityManagerInterface);
       $results=$leadsRepository->selectLeadReport($startDate, $endDate, $campaignId, $supplierId, $status, $entityManagerInterface);
      
    }
        return $this->render('home/resultAffiliate.html.twig', [

            'resultsGlobal'=>$resultsGlobal,
            'results'=>$results,
            'chart' =>$chart

        ]);
    }
}

function getBetweenDatesAffiliates($startDate, $endDate)
    {
        $rangArray = [];
            
        $startDate = strtotime($startDate);
        $endDate = strtotime($endDate);
             
        for ($currentDate = $startDate; $currentDate <= $endDate; 
                                        $currentDate += (86400)) {
                                                
            $date = date('Y-m-d', $currentDate);
            $rangArray[] = $date;
        }
  
        return $rangArray;
    }

 function chartSearchAffiliates( $datesArr, $leadPerday, $chartBuilder):Chart
    {
        $chart = $chartBuilder->createChart(Chart::TYPE_BAR);
        $chart->setData([
            'labels' => $datesArr,
            'datasets' => [
                [
                    'label' => 'leads',
                    'backgroundColor' => 'rgb(255, 99, 132)',
                    'borderColor' => 'rgb(255, 99, 132)',
                    
                    'data' => $leadPerday,
                    'responsive'=> true,
                ],
            ],
        ]);

        $chart->setOptions([
            'scales' => [
                'y' => [
                    'suggestedMin' => 0,
                    'suggestedMax' => 100,
                ],
            ],
            'maintainAspectRatio'=> false,
        ]);
        return $chart;
    }

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <div class="justify-content-center w-100 text-center">
        <h2 class="h2 my-5">Weclome on your Dashboard</h2>
        <p>select the dates for which you want your report:</p>
        <div class="mt-1">
        {% include "home/reportForm.html.twig" %}
        </div>
    </div>
{% else %}
{% include "home/login.html.twig" %}
{% endif %}
{% endblock %}

{% block footer %}
     {% include "footer.html.twig" %}
{% endblock %}

templates/home/login.html.twig
<section class="container-fluid" style="background-image: url(' {{ asset("../assets/images/backgroundLogin.jpg") }} ');
       repeat: no-repeat; background-repeat: no-repeat; background-size: cover; height: 87vh;">
<div class="row justify-content-center align-items-center rowLogin">
    <div class="col-lg-4">
        <form action="{{ path('app_login') }}" method="post">
            {% if error %}
                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}
            {% if app.user %}
                <div class="mb-3">
                    You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                </div>
            {% endif %}

            <h1 class="h3 mb-3 font-weight-normal mt-5 text-white">Welcome to RenovadsData, please log in! and consult your stats</h1>
                <label for="inputEmail" class="text-white">Email</label>
                <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
            <label for="inputPassword" class="text-white mt-3">Password</label>
            <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
            <div class="row">
            <a href="{{ path('app_forgot_password_request') }}" class="text-white">Forgotten password</a>
            <div class="col-6">
                <button class="btn btn-lg btn-secondary mt-3 px-5" type="submit">Sign in</button> 
                </div> 
                <div class="col-6">
                    <a href="{{ path('app_register') }}" class="btn btn-lg btn-primary mt-3 px-5">Register</a>
                </div>
            </div>
               </div>
            </div>
    </section>
</form>

templates/home/reportForm.html.twig
{% block body %}


    <form action="{{path('app_profile_result')}}" method="post">
    
        <input class="rounded" type="datetime-local" name="startDate" id="startDate">
        <input class="rounded" type="datetime-local" name="endDate" id="enDate">
        <input  class="btn btn-primary" type="submit" name="search" id="search" value="Search">

    </form>
{% endblock %}

templates/home/resultAffiliate.html.twig
{% extends 'base.html.twig' %}

{% block content_title %}Report{% endblock %}
{% block body %}
 <div class=" container justify-content-center mt-5 w-100 text-center">
{% include "home/reportForm.html.twig" %}

    <div class="row justify-content-center">
        <div class="col-12" style="height: 40vh">
        {{ render_chart(chart) }}
        </div>
    </div>
        <table class="table mt-4">
            <thead>
                <tr>
                    <th scope="col-6 col-lg-4">Id</th>
                    <th scope="col-6 col-lg-4">timestamp</th>
                    <th scope="col-6 col-lg-4">email</th>
                    <th scope="col-6 col-lg-4">Supplier</th>
                </tr>
            </thead>
            <tbody>
            {% for result in results %}
                <tr>
                        <th scope="row">{{result.lead_id_id}}</th>
                        <td>{{result.created_at}}</td>
                        <td>{{result.email}}</td>
                        <td>{{result.reference}}</td>

                        
                    </tr>
            {% endfor %}

                

            </tbody>
        </table>

</div>
{% endblock %}
 {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
    {% endblock %}